import pandas as pd
import matplotlib.pyplot as plt # matplotlib is a library downloaded to allow data to be plotted on a graph
df = pd.read_csv(r'/Users/faye/PycharmProjects/project/sales.csv') # this is the first dataset/dataframe
df2 = pd.read_csv(r'/Users/faye/PycharmProjects/project/sales_1.csv') # this is the second dataframe
# total sales(global scope)
sum_total_sales = df['total sales'].sum()
# total sales of each product
cleanser_sales = df['sales cleanser'].sum()
exfoliator_sales = df['sales exfoliator'].sum()
moisturiser_sales = df['sales moisturiser'].sum()
def total():
    print('total sales: {}'.format(sum_total_sales))
total()
# total sales
def total_sales():
    print('we have sold {} amount of cleanser'.format(cleanser_sales))
    print('we have sold {} amount of exfoliator'.format(exfoliator_sales))
    print('we have sold {} amount of moisturiser'.format(moisturiser_sales))
total_sales()
# most popular product
def popular_product():
    if moisturiser_sales > exfoliator_sales and moisturiser_sales > cleanser_sales:
        print('Moisturiser is our best seller!')
    elif exfoliator_sales > cleanser_sales and exfoliator_sales > moisturiser_sales: # elif statements
        print('Exfoliator is our best seller!')
    else:
        print("Cleanser is our best seller!")
popular_product()
# best months
def popular_month():
    #links months and total sales column together
    month_sales = df['total sales'].astype(str) + ' ' + df['month']
    max1 = month_sales.max()
    min1 = month_sales.min()
    print('Best Month: ' + str(max1))
    print('Worst Month: ' +str(min1))
popular_month()
# profits
def profits():
    cleanser_retail_price = df2.iloc[0]['cleanser'] # iloc is used to identify a particular cell on a spreadsheet
    total_retail_price_cleansers = cleanser_retail_price*cleanser_sales
    # print('The total amount we have generated from cleanser sales is £{}'.format(total_retail_price_cleansers))
    cleanser_wholesale_price = df2.iloc[1]['cleanser']
    total_wholesale_price_cleansers = cleanser_wholesale_price*cleanser_sales
    # print('The total amount our business spent on cleanser sales is £{}'.format(total_wholesale_price_cleansers))
    cleanser_profit = total_retail_price_cleansers - total_wholesale_price_cleansers
    print('We have made this much in profit from cleansers £{}'.format(cleanser_profit))
    moisturiser_retail_price = df2.iloc[0]['moisturiser']
    total_retail_price_moisturisers = moisturiser_retail_price*moisturiser_sales
    # print('The total amount we have generated from moisturiser sales is £{}'.format(total_retail_price_moisturisers))
    moisturiser_wholesale_price = df2.iloc[1]['moisturiser']
    total_wholesale_price_moisturisers = moisturiser_wholesale_price*moisturiser_sales
    # print('The total amount our business spent on moisturiser sales is £{}' .format(total_wholesale_price_moisturisers))
    moisturiser_profit = total_retail_price_moisturisers - total_wholesale_price_moisturisers
    print('We have made this much in profit from moisturisers £{}'.format(moisturiser_profit))
    exfoliator_retail_price = df2.iloc[0]['exfoliator']
    total_retail_price_exfoliators = exfoliator_retail_price*exfoliator_sales
    # print('The total amount we have generated from exfoliator sales is £{}'.format(total_retail_price_exfoliators))
    exfoliator_wholesale_price = df2.iloc[1]['exfoliator']
    total_wholesale_price_exfoliators = exfoliator_wholesale_price*exfoliator_sales
    # print('The total amount our business spent on exfoliator sales is £{}'.format(total_wholesale_price_exfoliators))
    exfoliator_profit = total_retail_price_exfoliators - total_wholesale_price_exfoliators
    print('We have made this much in profit from exfoliators £{}'.format(exfoliator_profit))
profits()
# percentages
def percentages():
    cleanser_sales = df['sales cleanser'].sum()
    a_number = cleanser_sales / sum_total_sales
    percentage_of_cleansers_cold = '{:.0%}'.format(a_number)
    print('the percentage of total sales generated from cleansers was {:.0%}'.format(a_number))
    a_number = exfoliator_sales / sum_total_sales
    percentage_of_exfoliators_sold = 'The percentage of total sales generated by exfoliators was {:.0%}'.format(a_number)
    print(percentage_of_exfoliators_sold)
    moisturiser_sales = df['sales moisturiser'].sum()
    a_number1 = moisturiser_sales / sum_total_sales
    percentage_of_moisturisers_sold = '{:.0%}'.format(a_number1)
    print('The percentage of total sales generated by moisturisers was ' + (percentage_of_moisturisers_sold))
percentages()
# graph of monthly sales
def graph():
    df_month_sales = df.iloc[:, 1:3]
    df3 = pd.DataFrame(df_month_sales,columns=['month','total sales'])
    df3.plot(x ='month', y='total sales', kind = 'line')
    plt.show()
graph()
percentages()
# graph of monthly sales
def graph():
    df_month_sales = df.iloc[:, 1:3]
    df3 = pd.DataFrame(df_month_sales,columns=['month','total sales'])
    df3.plot(x ='month', y='total sales', kind = 'line')
    plt.show()
graph()